Repository codestates-seb/seb41_main_014, pull requests merged in 2023-01, with the labels that each got.

#24 [BE Feat] Swagger 적용 위한 gradle dependency 추가 및 config 구성
  server/build.gradle
  server/src/main/java/com/team1472/moas/config/SwaggerConfig.java
  server/src/main/java/com/team1472/moas/goal/controller/GoalController.java
  server/src/main/java/com/team1472/moas/goal/dto/GoalPatchReq.java
  server/src/main/java/com/team1472/moas/goal/dto/GoalPostReq.java
  server/src/main/java/com/team1472/moas/goal/mapper/GoalMapper.java
  server/src/main/java/com/team1472/moas/goal/service/GoalService.java
Labels: documentation, enhancement

#25 [BE Feat] 목표 진척도 알고리즘 구현
  server/src/main/java/com/team1472/moas/goal/dto/GoalPatchRes.java
  server/src/main/java/com/team1472/moas/goal/dto/GoalPostRes.java
  server/src/main/java/com/team1472/moas/goal/dto/GoalRes.java
  server/src/main/java/com/team1472/moas/goal/entity/Goal.java
  server/src/main/java/com/team1472/moas/goal/service/GoalService.java
Labels: enhancement

#26 [BE Feat] 적금 리스트 필터링 조회 기능 구현
  server/build.gradle
  server/src/main/java/com/team1472/moas/config/QueryDslConfig.java
  server/src/main/java/com/team1472/moas/installment_savings/controller/SavingProductsController.java
  server/src/main/java/com/team1472/moas/installment_savings/dto/SavingProductRes.java
  server/src/main/java/com/team1472/moas/installment_savings/dto/SavingsFilteringReq.java
  server/src/main/java/com/team1472/moas/installment_savings/repository/CustomSavingProductsRepository.java
  server/src/main/java/com/team1472/moas/installment_savings/repository/CustomSavingProductsRepositoryImpl.java
  server/src/main/java/com/team1472/moas/installment_savings/repository/InterestRateRepository.java
  server/src/main/java/com/team1472/moas/installment_savings/service/SavingProductsService.java
  server/src/main/java/com/team1472/moas/response/PageInfo.java
Labels: enhancement

#33 [BE Feat] 적금 조회 시 세후 이자 계산 구현
  server/build.gradle
  server/src/main/java/com/team1472/moas/installment_savings/controller/SavingProductsController.java
  server/src/main/java/com/team1472/moas/installment_savings/dto/SavingProductRes.java
  server/src/main/java/com/team1472/moas/installment_savings/dto/SavingsFilteringReq.java
  server/src/main/java/com/team1472/moas/installment_savings/repository/CustomSavingProductsRepositoryImpl.java
  server/src/main/java/com/team1472/moas/installment_savings/service/SavingProductsService.java
Labels: documentation

#35 [BE Refactor] Open Api 적금 상품 조회 후 DB 저장 기능 리팩터링
  server/src/main/java/com/team1472/moas/installment_savings/controller/OpenApiController.java
  server/src/main/java/com/team1472/moas/installment_savings/entity/InstallmentSavings.java
  server/src/main/java/com/team1472/moas/installment_savings/entity/InterestRate.java
  server/src/main/java/com/team1472/moas/installment_savings/service/OpenApiService.java
Labels: documentation

#36 [BE Feat] 네이버 검색 Open API 연결
  server/src/main/java/com/team1472/moas/goal/controller/NaverSearchApiController.java
  server/src/main/java/com/team1472/moas/goal/service/NaverSearchApiService.java
  server/src/main/java/com/team1472/moas/util/secret/OpenApiAuthKey.java
Labels: enhancement

#48 [BE Feat] 관심 적금 삭제 기능 구현
  server/src/main/java/com/team1472/moas/exception/ExceptionCode.java
  server/src/main/java/com/team1472/moas/like_savings/controller/LikeSavingsController.java
  server/src/main/java/com/team1472/moas/like_savings/repository/CustomLikeSavingsRepository.java
  server/src/main/java/com/team1472/moas/like_savings/repository/CustomLikeSavingsRepositoryImpl.java
  server/src/main/java/com/team1472/moas/like_savings/repository/LikeSavingsRepository.java
  server/src/main/java/com/team1472/moas/like_savings/service/LikeSavingsService.java
Labels: enhancement

#49 [BE Feat] 회원 별 관심 적금 목록 조회 기능 구현
  server/src/main/java/com/team1472/moas/like_savings/controller/LikeSavingsController.java
  server/src/main/java/com/team1472/moas/like_savings/dto/LikeSavingProductsRes.java
  server/src/main/java/com/team1472/moas/like_savings/entity/LikeSavings.java
  server/src/main/java/com/team1472/moas/like_savings/repository/CustomLikeSavingsRepository.java
  server/src/main/java/com/team1472/moas/like_savings/repository/CustomLikeSavingsRepositoryImpl.java
  server/src/main/java/com/team1472/moas/like_savings/service/LikeSavingsService.java
Labels: enhancement

#52 [BE Fix] 적금 필터링 조회 기능 페이지네이션 수정
  server/src/main/java/com/team1472/moas/installment_savings/repository/CustomSavingProductsRepositoryImpl.java
Labels: documentation

#55 [BE Feat] 적금 정보 모두 삭제 기능 구현
  server/src/main/java/com/team1472/moas/installment_savings/controller/OpenApiController.java
Labels: documentation

#61 [BE MISC] 관심 적금 도메인 token 적용
  server/src/main/java/com/team1472/moas/like_savings/controller/LikeSavingsController.java
Labels: documentation

#65 [BE_MISC] 적금 필터링 조회 시 관심 적금 여부 확인 여부 추가
  server/src/main/java/com/team1472/moas/installment_savings/controller/SavingProductsController.java
  server/src/main/java/com/team1472/moas/installment_savings/dto/SavingProductRes.java
  server/src/main/java/com/team1472/moas/installment_savings/repository/CustomSavingProductsRepository.java
  server/src/main/java/com/team1472/moas/installment_savings/repository/CustomSavingProductsRepositoryImpl.java
  server/src/main/java/com/team1472/moas/installment_savings/service/SavingProductsService.java
Labels: documentation
